/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sia2_readdb_test_class */

#ifndef _Included_sia2_readdb_test_class
#define _Included_sia2_readdb_test_class
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sia2_readdb_test_class
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sia2_1readdb_test_1class_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
