/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sia2_readdb_readDB */

#ifndef _Included_sia2_readdb_readDB
#define _Included_sia2_readdb_readDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sia2_readdb_readDB
 * Method:    cgetData
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sia2_1readdb_readDB_cgetData
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     sia2_readdb_readDB
 * Method:    stringarray
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sia2_1readdb_readDB_stringarray
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
