/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sia2_readdb_readDB */

#ifndef _Included_sia2_readdb_readDB
#define _Included_sia2_readdb_readDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sia2_readdb_readDB
 * Method:    cgetData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sia2_1readdb_readDB_cgetData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
